// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh9HIoOxcUDf7hihNeXavK2oY-9-Ek1uM',
    appId: '1:887711704883:web:d81f03b6a91cd3198a4046',
    messagingSenderId: '887711704883',
    projectId: 'airbnb-clone-4ab63',
    authDomain: 'airbnb-clone-4ab63.firebaseapp.com',
    storageBucket: 'airbnb-clone-4ab63.firebasestorage.app',
    measurementId: 'G-DF4VVB4KHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA712HuCHBvg8UPs4zBJSKQQ0TlXAaFdNc',
    appId: '1:887711704883:android:d734375a233d5a118a4046',
    messagingSenderId: '887711704883',
    projectId: 'airbnb-clone-4ab63',
    storageBucket: 'airbnb-clone-4ab63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6tufnTjSyfPtDjlBCBSK9iC2oHjSzs_E',
    appId: '1:887711704883:ios:0ba27737f0a24c1d8a4046',
    messagingSenderId: '887711704883',
    projectId: 'airbnb-clone-4ab63',
    storageBucket: 'airbnb-clone-4ab63.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6tufnTjSyfPtDjlBCBSK9iC2oHjSzs_E',
    appId: '1:887711704883:ios:0ba27737f0a24c1d8a4046',
    messagingSenderId: '887711704883',
    projectId: 'airbnb-clone-4ab63',
    storageBucket: 'airbnb-clone-4ab63.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh9HIoOxcUDf7hihNeXavK2oY-9-Ek1uM',
    appId: '1:887711704883:web:e95efe245d5757618a4046',
    messagingSenderId: '887711704883',
    projectId: 'airbnb-clone-4ab63',
    authDomain: 'airbnb-clone-4ab63.firebaseapp.com',
    storageBucket: 'airbnb-clone-4ab63.firebasestorage.app',
    measurementId: 'G-1RSDMYPCKV',
  );
}
